# frozen_string_literal: true

# Bulk seed for development / load testing. Replaces all rows in `employees` with COUNT
# synthetic records. Uses insert_all in batches (no per-row validations/callbacks) for speed.
#
# Full names are generated by independently sampling first_names.txt and last_names.txt
# (see db/data/). Set SEED_RANDOM to an integer for reproducible output.
#
#   SEED_RANDOM=42 bin/rails db:seed

require "bigdecimal"

module EmployeesBulkSeed
  COUNT = 10_000
  BATCH = 2_000

  JOB_TITLES = [
    "Software Engineer", "Senior Software Engineer", "Staff Engineer", "Principal Engineer",
    "Engineering Manager", "Director of Engineering", "Product Manager", "Product Designer",
    "UX Researcher", "Data Analyst", "Data Scientist", "Machine Learning Engineer",
    "DevOps Engineer", "Site Reliability Engineer", "Security Engineer", "QA Engineer",
    "Technical Writer", "Solutions Architect", "Sales Engineer", "Account Executive",
    "Customer Success Manager", "Support Engineer", "Finance Analyst", "Accountant",
    "HR Business Partner", "Recruiter", "Legal Counsel", "Office Manager", "Operations Analyst",
    "Business Analyst", "Marketing Manager", "Content Strategist", "Paralegal"
  ].freeze

  # Valid ISO-3166 alpha-2 + ISO-4217 triplets used by Employee validations.
  COUNTRY_CURRENCY = [
    %w[US USD], %w[GB GBP], %w[DE EUR], %w[FR EUR], %w[CA CAD], %w[AU AUD], %w[JP JPY],
    %w[IN INR], %w[NL EUR], %w[SE SEK], %w[CH CHF], %w[BR BRL], %w[MX MXN], %w[IE EUR],
    %w[IT EUR], %w[ES EUR], %w[SG SGD], %w[KR KRW], %w[NO NOK], %w[DK DKK], %w[PL PLN],
    %w[AT EUR], %w[BE EUR], %w[FI EUR], %w[PT EUR], %w[NZ NZD], %w[ZA ZAR]
  ].freeze

  DEPARTMENTS = [
    "Engineering", "Product", "Sales", "Marketing", "Operations",
    "Finance", "Human Resources", "Legal", "Customer Success", "Research"
  ].freeze

  class << self
    def call
      if Rails.env.production?
        warn "EmployeesBulkSeed: skipped (destructive bulk replace is disabled in production)."
        return
      end

      first_names, last_names = load_name_lists
      rng = build_rng
      now = Time.current
      hire_start = Date.new(1999, 1, 1)
      hire_span_days = [ (Date.current - hire_start).to_i, 1 ].max

      t0 = Process.clock_gettime(Process::CLOCK_MONOTONIC)
      ActiveRecord::Base.transaction do
        Employee.delete_all

        1.upto(COUNT).each_slice(BATCH) do |indices|
          rows = indices.map do |i|
            build_row(
              i,
              rng: rng,
              first_names: first_names,
              last_names: last_names,
              now: now,
              hire_start: hire_start,
              hire_span_days: hire_span_days
            )
          end
          Employee.insert_all!(rows)
        end
      end
      seconds = Process.clock_gettime(Process::CLOCK_MONOTONIC) - t0

      warn format("EmployeesBulkSeed: inserted %<count>d rows in %<sec>.3fs", count: COUNT, sec: seconds)
    end

    private

    def load_name_lists
      root = Rails.root.join("db/data")
      first_path = root.join("first_names.txt")
      last_path = root.join("last_names.txt")

      first_names = File.readlines(first_path, chomp: true).map(&:strip).reject(&:empty?).uniq
      last_names = File.readlines(last_path, chomp: true).map(&:strip).reject(&:empty?).uniq

      raise "Missing or empty #{first_path}" if first_names.empty?
      raise "Missing or empty #{last_path}" if last_names.empty?

      [ first_names, last_names ]
    end

    def build_rng
      seed =
        if ENV["SEED_RANDOM"].present?
          Integer(ENV["SEED_RANDOM"])
        else
          Random.new_seed
        end
      Random.new(seed)
    end

    def build_row(i, rng:, first_names:, last_names:, now:, hire_start:, hire_span_days:)
      country, currency = COUNTRY_CURRENCY.sample(random: rng)
      salary_cents = rng.rand(3_500_000..19_999_999) # $35,000.00 .. $199,999.99
      salary = BigDecimal(salary_cents) / 100

      status =
        case rng.rand(100)
        when 0...78 then 0 # active
        when 78...93 then 1 # on_leave
        else 2 # terminated
        end

      hired_on = hire_start + rng.rand(0..hire_span_days)

      department =
        if rng.rand < 0.72
          DEPARTMENTS.sample(random: rng)
        end

      {
        "first_name" => first_names.sample(random: rng),
        "last_name" => last_names.sample(random: rng),
        "job_title" => JOB_TITLES.sample(random: rng),
        "country" => country,
        "currency" => currency,
        "salary" => salary,
        "email" => format("seed.employee.%05d@example.invalid", i),
        "department" => department,
        "hired_on" => hired_on,
        "employment_status" => status,
        "employee_number" => format("SEED%07d", i),
        "created_at" => now,
        "updated_at" => now
      }
    end
  end
end
